version: '3'

services:
  web:
    build: .
    ports:
    #running on port 5000, because my other project is running on port 80
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development